### ISSUE TITLE
ts-devrant

### ISSUE THREAD

**Issue by dr010001111** [devRant-Community/awesome-devrant#15]
Sort of port of RantScript in TypeScript with typed responses. Already includes some api fixes and additional endpoints.

Will diff my observations against the existing api doc when I have more time.

https://github.com/dr010001111/ts-devrant

@frogstair

**Comment by jonasgeiler** [comment]
Thanks! 

Could you do a PR?
would save me some time 😅

**Comment by dr010001111** [comment]
There you go bud
