### ISSUE TITLE
Add devrant as repo website

### ISSUE THREAD

**Issue by 7twin** [devRant-Community/awesome-devrant#8]
I could just add it, but would like some input on this first, many awesome lists that are dedicated to a specific community/framework/.., have the website of the repo set to the main url - in our example it would be a link to https://devrant.com

I think it could both avoid from people having to google what devrant is and also drive some traffic

**Comment by jonasgeiler** [comment]
Alright. Sounds good!

**Comment by jonasgeiler** [comment]
You can do it!

**Comment by 7twin** [comment]
@Skayo apparently I was wrong and only the repo owner can do that

**Comment by jonasgeiler** [comment]
Will do. Didn't know either
